const p = 10;
console.log("p value before {}: " + p);
{
    //console.log("p value after {}: " + p);
    //p = 20;
    //console.log("p value in {} and after = action: " + p);
    const p = 100;
    console.log("p value before {} and after repeat const: " + p);
}
console.log("p value after {}: " + p);
//p = 30;
//console.log("p value after {} and after = action: " + p);
//const p = 40;
//console.log("p value after {} and after repeat const: " + p);