let y = 10;
console.log("y value before {}: " + y);
{
    //console.log("y value after {}: " + y);
    //y = 20;
    //console.log("y value in {} and after = action: " + y);
    let y = 100;
    console.log("y value before {} and after repeat let: " + y);
}
console.log("y value after {}: " + y);
y = 30;
console.log("y value after {} and after = action: " + y);
//let y = 40;
console.log("y value after {} and after repeat let: " + y);